services:

  # Feed Ingestion Service
  feed-ingestion:
    build: ./feed-ingestion-service
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - sportsbet-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Data Processing Service
  data-processing:
    build: ./data-processing-service
    ports:
      - "4001:3000"
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - MYSQL_HOST=mysql
      - MYSQL_USER=sportsbet
      - MYSQL_PASSWORD=sportsbetpass
      - MYSQL_DATABASE=sportsbet
      - MYSQL_PORT=3307
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=debug
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sportsbet-network

  # Data Distribution Service
  data-distribution:
    build: ./data-distribution-service
    ports:
      - "4002:5000"  # HTTP API
      - "4003:5001"  # WebSocket
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=sportsbet
      - MYSQL_PASSWORD=sportsbetpass
      - MYSQL_DATABASE=sportsbet
      - REDIS_URL=redis://redis:6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sportsbet-network

  test-feed-generator:
    build:
      context: ./test-feed-generator
      dockerfile: Dockerfile
    ports:
      - "4004:3000"
    environment:
      - INGESTION_SERVICE_URL=http://feed-ingestion:3000
      - INTERVAL_MS=5000
    depends_on:
      - feed-ingestion
    networks:
      - sportsbet-network

  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - sportsbet-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sportsbet-network

  # MySQL
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sportsbet
      MYSQL_USER: sportsbet
      MYSQL_PASSWORD: sportsbetpass
      MYSQL_INNODB_BUFFER_POOL_SIZE: 256M
      MYSQL_INNODB_LOG_FILE_SIZE: 64M
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sportsbet-network

  # Redis
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sportsbet-network

networks:
  sportsbet-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: